### ISSUE TITLE
Save output to file

### ISSUE THREAD

**Issue by ahes** [julmon/pg_activity#100]
Hi,

it would be great if pg_activity support batch mode like in `top` command.

```
pg_activity [OPTIONS] [delay [count]] 
```

For example to read data once and store it to file I would use:
```
pg_activity 1 1 > /tmp/pg_activity.output
```

Do you think it is possible to implement?
The simplest version of that would be to support file redirection: `pg_activity > output.txt`

**Comment by julmon** [comment]
https://github.com/julmon/pg_activity/pull/99 fixed it
