### ISSUE TITLE
Waiting / Blocking view glitch in 1.5.0

### ISSUE THREAD

**Issue by kmoppel** [julmon/pg_activity#119]
Seems "type" / "relation" columns have been shifted, some weird numbers are being shown
![pg_actvity_blocking](https://user-images.githubusercontent.com/346788/62708999-347d4480-b9fd-11e9-885f-d4363fb21399.png)
![pg_actvity_waiting](https://user-images.githubusercontent.com/346788/62709000-347d4480-b9fd-11e9-8a29-3fce4993503b.png)

**Comment by julmon** [comment]
Thanks for the report. Should be fixed now.
