### ISSUE TITLE
Option to cancel query on backend

### ISSUE THREAD

**Issue by gelias** [julmon/pg_activity#36]

**Comment by julmon** [comment]
Hi,

This is already available through the 'k' key hit in interactive mode.

Thanks,

**Comment by fabriziomello** [comment]
@julmon actually pg_activity always use "pg_terminate_backend" if the PG version >= 8.4 (https://github.com/julmon/pg_activity/blob/master/pgactivity/Data.py#L206)

Our intention is provide a way to operator just cancel queries instead of to kill the backend.

**Comment by julmon** [comment]
Alright, will think about this.

Thanks,

**Comment by fabriziomello** [comment]
@julmon thanks. Soon we'll send a pull request.

**Comment by julmon** [comment]
@fabriziomello great.
