### ISSUE TITLE
FATAL: float() argument must be a string or a number

### ISSUE THREAD

**Issue by mjallday** [julmon/pg_activity#37]
I'm seeing this when running pg_activity on ubuntu 12.04

There is no stack trace or any additional details provided when it crashes, this occurs on many postgres installs when running pg_activity locally and connecting to a 9.1 installation. 

I have not tried against other postgres versions. 

This is version 1.0.2 installed via pip

**Comment by julmon** [comment]
Hi,

Latest version (1.2.0) has just been pushed to pypi.

Thanks,
