### ISSUE TITLE
Depraction: warning get_memory_percent()  is depracted

### ISSUE THREAD

**Issue by forall** [julmon/pg_activity#39]
Hi,

It's possible to fix this problem in your software? I used this tools on my database server CentOS 5.11 x64 and I have this error. I saw someone send to repo a fix this problem but it's not apply..

**Comment by datasaur** [comment]
PR 35 addresses this: https://github.com/julmon/pg_activity/pull/35

**Comment by forall** [comment]
Ok, I saw this and when will be add to project?

**Comment by julmon** [comment]
Hi,

Commit https://github.com/julmon/pg_activity/commit/f00fc2af6fd08ffc0f98d2f35fcf08c7a3057590 must resolve this issue. A new release (1.2.0) is out including this fix.

Thanks,

**Comment by forall** [comment]
Hi julmon, I install a new version pg_activity with commit (f00fc2a), but on my CentOS 5.11 x64 I still have problem with this error #35

**Comment by julmon** [comment]
Hi,

Just merged PR35, should fix it : https://github.com/julmon/pg_activity/commit/8a799cceef9d3c6afde6f77bc5d64a730dac9ea0
