### ISSUE TITLE
Add application_name in display option

### ISSUE THREAD

**Issue by AceSlash** [julmon/pg_activity#40]
Hello,

pg_activity is incredibly useful but it miss a critical feature: the "application_name" cannot be displayed.

Could you please add a display option for this field?

**Comment by sebastianwebber** [comment]
Hi There,

Did you mean a new column to show the application name or just pg_activity show its name when connect to PostgreSQL?

**Comment by AceSlash** [comment]
I meant a new column.

**Comment by pashagolub** [comment]
+1 from me. Extremely useful improvement
