### ISSUE TITLE
pg_activity exits with FATAL: must be string, not int on launch

### ISSUE THREAD

**Issue by conorao** [julmon/pg_activity#42]
Hi-

I installed pg_activity and also installed a postgres server on my local machine to test this before using it on a remote database. I have a system user named ```postgres``` that has full access to the database server. However, when using the provided command: ```sudo -u postgres pg_activity -U postgres``` the program terminates with ```FATAL: must be string, not int```

**Comment by src386** [comment]
Same here.

**Comment by julmon** [comment]
Hi,

Which pg_activity version is it ?

**Comment by src386** [comment]
1.3.0 dev

**Comment by julmon** [comment]
Could you start it with the --debug option ?
Thank you.

**Comment by jchumnanvech** [comment]
I had the same issue. To get it working I reverted to checkout 5f7a965ecdb729b49006c758065d1b300f36e89c and reinstalled and it worked.

I ran it with --debug on latest commit (1cb5862) and I got 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pg_activity-1.3.0-py2.7.egg/EGG-INFO/scripts/pg_activity", line 340, in main
  File "build/bdist.linux-x86_64/egg/pgactivity/UI.py", line 1790, in refresh_window
    total_size)
  File "build/bdist.linux-x86_64/egg/pgactivity/UI.py", line 1562, in __print_header
    self.__get_color(C_CYAN))
  File "build/bdist.linux-x86_64/egg/pgactivity/UI.py", line 1452, in __print_string
    self.win.addstr(lineno, colno, word, color)
TypeError: must be string, not int
FATAL: must be string, not int

**Comment by julmon** [comment]
Thank you. This is now fixed.

Regards.
