### ISSUE TITLE
FATAL: 'PSProcess' object has no attribute 'get_memory_percent'

### ISSUE THREAD

**Issue by hassek** [julmon/pg_activity#44]
I am having this error when trying to run this on postgresql 9.4

**Comment by julmon** [comment]
Hi,

What ```pg_activity``` and ```psutil``` versions  are they ?
To get it, you could try this:

```
$ pg_activity --version
```

```
$ python
[...]
>>> import psutil
>>> psutil.__version__
'2.1.1'
>>> 
```

Regards,

**Comment by hassek** [comment]
Here are both versions:

    pg_activity 1.2.0
    >>> import psutil
    >>> psutil.__version__
    '3.2.1'

Bests,

**Comment by smant** [comment]
Have the same problem
```
ubuntu 12.04.4
pg_activity 1.2.0
psutil 3.2.2
```

**Comment by donatello** [comment]
I have have the same problem with latest release (1.2.0) and psutil 3.2.2.

But I tried out the latest master, and it appears to be resolved there - @smant @hassek

**Comment by matkro** [comment]
Same error here with psutils 3.0.1 and 1.2.0 :/  
Git master works for me with psutils 3.0.1.
Any release planned/soon?

**Comment by julmon** [comment]
> Any release planned/soon?

Done: https://github.com/julmon/pg_activity/releases/tag/v1.3.0
