### ISSUE TITLE
Incompatible with 9.6RC1

### ISSUE THREAD

**Issue by RoelAdriaans** [julmon/pg_activity#53]
Postgresql 9.6 RC1 has been released, and there are some changes in the schematic.

When you run pg_activity you get the error: 
```
$ pg_activity
FATAL: column pg_stat_activity.waiting does not exist
LINE 11:         pg_stat_activity.waiting AS wait,
                 ^
```

From the RC release notes ( https://www.postgresql.org/docs/9.6/static/release-9-6.html ):

> Improve the pg_stat_activity view's information about what a process is waiting for (Amit Kapila, Ildus Kurbangaliev)
> 
> Historically a process has only been shown as waiting if it was waiting for a heavyweight lock. Now waits for lightweight locks and buffer pins are also shown in pg_stat_activity. Also, the type of lock being waited for is now visible. These changes replace the waiting column with wait_event_type and wait_event.
> 

New pg_stat_activity information: 
https://www.postgresql.org/docs/9.6/static/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW

**Comment by devrimgunduz** [comment]
So, shall we expect a new release? I just got a complaint from an RPM user about broken pg_activity for 9.6. Thanks!

**Comment by julmon** [comment]
Hi Devrim,

Yes, I plan to make a new release ASAP.

Thanks,

**Comment by julmon** [comment]
The new release: https://github.com/julmon/pg_activity/releases/tag/v1.3.1
