### ISSUE TITLE
pg_activity on postgresql 9.6 - ERROR: column pg_stat_activity.waiting does not exist

### ISSUE THREAD

**Issue by sathiyasarathi** [julmon/pg_activity#56]
Tried invoking the pg_stat_activity tool for PostgreSQL 9.6 

`FATAL: column pg_stat_activity.waiting does not exist
LINE 11:         pg_stat_activity.waiting AS wait,
                 ^
`
Is there a possible workaround for this issue?

**Comment by RoelAdriaans-B-informed** [comment]
Fixed in newest relaase: The new release: https://github.com/julmon/pg_activity/releases/tag/v1.3.1 
See issue #53
