### ISSUE TITLE
PostgreSQL 10 compatible release?

### ISSUE THREAD

**Issue by jorsol** [julmon/pg_activity#67]
Issue #64 / #65  to add support for Pg10 was merged on 21 Jul, any reason to not release a Pg10 compatible version of pg_activity?

**Comment by Zolmeister** [comment]
I get this error with postgres 10.0:

```
FATAL: Undefined PostgreSQL version.
```

**Comment by sannek8552** [comment]
+1

**Comment by julmon** [comment]
Here it is : https://github.com/julmon/pg_activity/releases/tag/v1.4.0

**Comment by jorsol** [comment]
Thanks!
