### ISSUE TITLE
PostgreSQL 10 parallel query duplicates

### ISSUE THREAD

**Issue by kmatt** [julmon/pg_activity#68]
When PG10 spawns multiple workers for a single query, pg_activity shows a query per worker in what at first appear to be multiple instances of the same query.

It would be a significant UI change, but perhaps as a future feature workers could be nested under the parent thread.

**Comment by julmon** [comment]
About nesting under the parent thread, I guess this implies to know "parent" PID.
ASFAIK, there is no way to know "parent" PID of a BGW. This information is not present in `pg_stat_activity` view, we can only know backend type, wich is `background worker` when the backend is a parallel worker. No internal function for this either.
On system side, as parallel worker process are not forked from the gather process but from the `postmaster`, I can't see how we can find this "parent" PID properly.
The dirty way could be by parsing process' name. Process name contains the PID we're looking for : `postgres: bgworker: parallel worker for PID XXXX`

Perhaps we can just distinguish background worker backend from others like this https://github.com/julmon/pg_activity/pull/69

Thoughts ?

**Comment by kmatt** [comment]
A simple backend worker flag makes sense, especially if getting the parent PID means adding a new interface to read system PID data.

**Comment by julmon** [comment]
Merged. Thank you for this feedback.
