### ISSUE TITLE
psutil warning message across top of pg_activity screen

### ISSUE THREAD

**Issue by haydentech** [julmon/pg_activity#74]
When I run pg_activity, I continually get this message across the top of the screen:

```
/usr2/python/lib/python2.7/site-packages/psutil/_pslinux.py:481: RuntimeWarning:
 shared memory stats couldn't be deter|
```

...and then it's cut off by the drawing of the header.  Another Python project that had this same warning has already pushed a fix to suppress it, so maybe we can use that same fix: https://github.com/dask/dask/issues/1588

**Comment by julmon** [comment]
@haydentech could you try this fix: https://github.com/julmon/pg_activity/pull/81 ?
