### ISSUE TITLE
Connecting via unix-domain socket is showing "None" on client column

### ISSUE THREAD

**Issue by michelmilezzi** [julmon/pg_activity#76]
Perhaps we could do something like the following to workaround this issue:

```
       CASE
           WHEN client_port=-1 THEN 'local pipe'
           WHEN length(client_hostname)>0 THEN client_hostname||':'||client_port
           ELSE textin(inet_out(client_addr))||':'||client_port
       END AS client
```
This is how client column is treated on [PgAdmin](https://github.com/postgres/pgadmin3/blob/794527d97e2e3b01399954f3b79c8e2585b908dd/pgadmin/frm/frmStatus.cpp#L1355).

A quote from the [docs](https://www.postgresql.org/docs/current/static/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW):

> IP address of the client connected to this backend. If this field is null, it indicates either that the client is connected via a Unix socket on the server machine or that this is an internal process such as autovacuum.

**Comment by julmon** [comment]
@michelmilezzi what do you think about this https://github.com/julmon/pg_activity/commit/f24ea894222778f3692cd8010fcee7af035a9f28 ?
