### ISSUE TITLE
Incorrect display for remote connection and complex multiline queries

### ISSUE THREAD

**Issue by pashagolub** [julmon/pg_activity#77]
I'm not sure if the remote connection is an issue, but decided to add it just in case.
The thing is for complex queries table is corrupted. Switching between views (V key) is not fixing the situation, but the display is changing somehow and stays corrupted.
![2018-06-10 19_47_36-greenshot](https://user-images.githubusercontent.com/9463113/41204673-0df1c7ea-6ce8-11e8-8209-5ee867d0d28c.png)

**Comment by genericmoniker** [comment]
I'm seeing something similar (though just connected to localhost). The displayed multi-line query is truncated in various surprising ways depending on the size of the terminal window. For example:

![image](https://user-images.githubusercontent.com/2375404/41747651-f0f4e532-756b-11e8-9f2d-7a6631a11444.png)

**Comment by julmon** [comment]
What terminal are you using ? It looks that pg_activity doesn't get terminal right size.

**Comment by pashagolub** [comment]
Terminal on the screenshot is ConEmu, but I observed pretty the same on others. Could it be affected by \r\n symbols in a SQL itself?

**Comment by julmon** [comment]
@pashagolub thanks ! you're right, query string wasn't cleaned in remote mode.

**Comment by genericmoniker** [comment]
In my case, it was just the Gnome terminal in CentOS 7, running in a VirtualBox VM.
